insert into t_tabuamember values (1,null,'F60WMT',null,null,1,'BEI/RONGHUA','brhsp123',null,null);
insert into t_tabuamember values (2,null,'LRSKM3',null,null,1,'CHEN/CANYAN','ccytbid123',null,null);
insert into t_tabuamember values (3,null,'CWVLWD',null,null,1,'CHOU/YAT MING','cymtb123',null,null);
insert into t_tabuamember values (4,null,'DCRHBQ',null,null,1,'DU/JINSHENG','djstb123',null,null);
insert into t_tabuamember values (5,null,'Q1BW7T',null,null,1,'CHAND/RAJESH','drtb123',null,null);
insert into t_tabuamember values (6,null,'HDF66J',null,null,1,'FENG/PEILIAN','fpltb123',null,null);
insert into t_tabuamember values (7,null,'XC2QTM',null,null,1,'HUNG/JIEYAU','hjy123',null,null);
insert into t_tabuamember values (8,null,'WW1JCN',null,null,1,'HUANG/LIQING','hlqtb123',null,null);
insert into t_tabuamember values (9,null,'XRMT3G',null,null,1,'JIA/JIN','jjtb123',null,null);
insert into t_tabuamember values (10,null,'VK48KW',null,null,1,'KAN/FENGJINYE','kfjytb123',null,null);
insert into t_tabuamember values (11,null,'H7KDHB',null,null,1,'KAN/SANLOK','ksltb123',null,null);
insert into t_tabuamember values (12,null,'0NR44K',null,null,1,'CHONG/KWONG FAI SAMUEL','KWONG1969',null,null);
insert into t_tabuamember values (13,null,'G07X78',null,null,1,'LI/HAOLIN','lhltb123',null,null);
insert into t_tabuamember values (14,null,'CVWGPM',null,null,1,'LIANG/LIHUA','llhtb123',null,null);
insert into t_tabuamember values (15,null,'S4F09J',null,null,1,'LI/XIAOYUN','lxytb123',null,null);
insert into t_tabuamember values (16,null,'RQ511S',null,null,1,'LI/YUE','lye123',null,null);
insert into t_tabuamember values (17,null,'0ZHVNP',null,null,1,'PHUA/SWEESENG','pstc123',null,null);
insert into t_tabuamember values (18,null,'SW4W4L',null,null,1,'SHI/QINFANG','sqftb123',null,null);
insert into t_tabuamember values (19,null,'P7QZSZ',null,null,1,'SUN/WENBIN','swbtb123',null,null);
insert into t_tabuamember values (20,null,'DFX84C',null,null,1,'ZHAO/FULI','tcfl123',null,null);
insert into t_tabuamember values (21,null,'KTVHGR',null,null,1,'HE/YONGJU','tchyj123',null,null);
insert into t_tabuamember values (22,null,'82DKT6',null,null,1,'TAN/CHUNKIAM','tcktb123',null,null);
insert into t_tabuamember values (23,null,'JQS3ZV',null,null,1,'ZHAO/MING','tczm123',null,null);
insert into t_tabuamember values (24,null,'RKX0WQ',null,null,1,'WANG/YUEHUA','wyhtc123',null,null);
insert into t_tabuamember values (25,null,'ZPSFZF',null,null,1,'YIP FUNG KWAI','yfktb123',null,null);
insert into t_tabuamember values (26,null,'FJZSQ0',null,null,1,'YE/SANFA','ysftb123',null,null);
insert into t_tabuamember values (27,null,'FRWVZ6',null,null,1,'ZHANG/YIFENG','ZYFTB123',null,null);
insert into t_tabuamember values (28,null,'N8FLWF',null,null,1,'ZHENG/ZIYI  ','zzytc123',null,null);
insert into t_tabuamember values (29,null,'PD7C5M',null,null,1,'LI/DONGMEI','ldmtb123',null,null);
